services:
  - type: web
    name: cricket-ultimate-frontend
    runtime: docker
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        value: "https://kollxlzqqgznfiutpqjz.supabase.co"
      - key: SUPABASE_ANON_KEY
        sync: false # Set manually in dashboard
