services:
  - type: static_site
    name: cricket-ultimate-frontend
    region: singapore
    plan: free
    branch: gh-pages
    publishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
