name: Deploy Flutter Web to OCI Object Storage

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Build Flutter Web
        run: flutter build web --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} --dart-define=SUPABASE_STORAGE_URL=${{ secrets.SUPABASE_STORAGE_URL }} --dart-define=BACKEND_URL=${{ secrets.BACKEND_URL }}

      # Deploy built frontend assets in build/web to OCI Object Storage
      - name: Synchronize Build Files with OCI Object Storage
        uses: oracle-actions/run-oci-cli-command@v1.3.0
        with:
          command: "os object sync --bucket-name ${{ secrets.OCI_BUCKET_NAME }} --namespace-name ${{ secrets.OCI_NAMESPACE }} --src-dir build/web --delete"
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
